project:
  type: website
  output-dir: docs

website:
  title: "ES114 - PSDV"
  favicon: images/psdv_favicon.jpeg
  navbar:
    logo: images/psdv_logo.jpeg
    right:
      - href: index.qmd
        text: Home
      - href: grading.qmd
        text: Grading & Leave Policy
      - href: faq.qmd
        text: FAQs
      - href: schedule.qmd
        text: Lectures
      - href: tentative.qmd
        text: Tentative Deadlines
      - href: https://nipunbatra.github.io
        text: Instructor Homepage

format:
  html:
    theme:
      light: [litera, styles.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
