project:
  type: website
  output-dir: docs

website:
  title: "ES114 - PSDV"
  favicon: images/psdv_favicon.svg
  navbar:
    logo: images/psdv_logo.svg
    right:
      - href: index.qmd
        text: Home
      - href: grading.qmd
        text: Grading & Leave Policy
      - href: faq.qmd
        text: FAQs
      - href: lectures.qmd
        text: Lectures
      - href: tentative.qmd
        text: Tentative Deadlines
      - href: videos/videos.qmd
        text: Exposition Submissions
      - href: https://nipunbatra.github.io
        text: Homepage

format:
  html:
    theme: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Source Sans 3"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
