---
title: "Lectures & Materials"
---

::: {.callout-tip}
## Course Resources

* 📚 [GitHub repository with source code for lectures and notebooks](https://github.com/nipunbatra/psdv-teaching)
* 📖 [Rendered Lecture notebooks](https://nipunbatra.github.io/psdv-teaching/notebooks.html)
* 🎥 [YouTube playlist with all recordings](https://www.youtube.com/watch?v=CAzR00au0T0&list=PLftoLyLEwECCTFpc8_-gV8NqG_LgdL3Uy&index=1) 

Content is updated as the course progresses. Click on any topic below to access materials.

:::

<div class="lectures-container">

| # | Date | Topic | Materials | 
| :-: | :------ | :--------------- | :------------ | 
|     0     | 06 Jan 2025 | Introduction and Logistics |  
|1| 07 Jan 2025| NumPy| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/intro-numpy.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=CAzR00au0T0" target="_blank">Youtube</a> |
|2| 08 Jan 2025| Lab 1: NumPy| <a href="https://colab.research.google.com/drive/169vg_FV35sJ8irVXU82RrTwlR762Ph2g?usp=sharing" target="_blank">Colab</a> |
|3| 13 Jan 2025| Pandas| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/introduction-pandas.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=iaQDhwFkAhA" target="_blank">Youtube</a> |
|4| 14 Jan 2025| Matplotlib| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/introduction-matplotlib.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=ERu46g5EzVk" target="_blank">Youtube</a> |
|5| 15 Jan 2025| Lab Viva 1|
|6| 20 Jan 2025| Lab 2: Pandas| <a href="https://colab.research.google.com/drive/1pmt8hSfwzhp8ke3uXsGrOt4XELdoTmr1?usp=sharing" target="_blank">Colab</a> |
|7| 21 Jan 2025| Set Theory| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/set.html" target="_blank">Notebook</a>, <a href="https://probability4datascience.com/slides/Slide_2_01.pdf" target="_blank">Slides</a> |
|8| 22 Jan 2025| Lab 2: Pandas (continued)|
|9| 23 Jan 2025| Jupyter Widgets| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/widgets.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=BJAaZaKxf00" target="_blank">YouTube</a> |
|10| 23 Jan 2025| More Set Theory Questions | <a href="https://colab.research.google.com/drive/1RrjF2VZDcst0iUgW5zrpsBy-VWUfjtkJ?usp=sharing" target="_blank">Colab</a> |
|11| 27 Jan 2025| Set Theory (continued)| <a href="https://probability4datascience.com/slides/Slide_2_01.pdf" target="_blank">Slides</a>, <a href="./slides/Set-Theory_27Jan.pdf" target="_blank">Handwritten Slides</a> |
|12| 28 Jan 2025| Probability| <a href="https://probability4datascience.com/slides/Slide_2_02.pdf" target="_blank">Slides1</a>, <a href="https://probability4datascience.com/slides/Slide_2_03.pdf" target="_blank">Slides2</a>, <a href="./slides/Probability_28Jan.pdf" target="_blank">Handwritten Slides</a> |
|13| 29 Jan 2025| Lab Viva 2|
|14| 03 Feb 2025| Conditional Probability & Independence | <a href="https://probability4datascience.com/slides/Slide_2_04.pdf" target="_blank">Slides Conditional</a>, <a href="https://probability4datascience.com/slides/Slide_2_05.pdf" target="_blank">Slides Independence</a>, <a href="./slides/Conditional_Bayes_3_4Feb.pdf" target="_blank">Handwritten Slides</a> |
|15| 04 Feb 2025| Bayes Theorem & Total Probability | <a href="https://probability4datascience.com/slides/Slide_2_06.pdf" target="_blank">Slides</a>, <a href="./slides/Conditional_Bayes_3_4Feb.pdf" target="_blank">Handwritten Slides (continued)</a> |
|16| 05 Feb 2025| Quiz 1|
|17| 10 Feb 2025| Random Variables + Quiz Discussion | <a href="https://probability4datascience.com/slides/Slide_3_01.pdf" target="_blank">Slides</a> |
|18| 11 Feb 2025| Probability Mass Function | <a href="https://probability4datascience.com/slides/Slide_3_02.pdf" target="_blank">Slides</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/pmf-discrete.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=_VU6QMC6XE0" target="_blank">YouTube</a> |
|19| 17 Feb 2025| Discrete RVs and Expectation | <a href="https://probability4datascience.com/slides/Slide_3_04.pdf" target="_blank">Slides</a>, <a href="./slides/Expectation-Moments-PMF_17_18Feb.pdf" target="_blank">Handwritten Slides PMF Expectation-Moments</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/expectation.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=sVBOSwT5K8I" target="_blank">YT Video on Binomial & Poisson</a> |
|20| 18 Feb 2025| Moments | <a href="https://probability4datascience.com/slides/Slide_3_05.pdf" target="_blank">Slides</a>, <a href="./slides/Expectation-Moments-PMF_17_18Feb.pdf" target="_blank">Handwritten Slides (continued)</a>, <a href="./slides/PDF.pdf" target="_blank">Handwritten Slides Continuous RV</a> |
|21| 19 Feb 2025| Lab Viva 3|
|22| 24 Feb 2025| Continuous RVs and Coin-Flip Game | <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/expectation.html" target="_blank">Notebook Expectation</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/pdf-continuous.html" target="_blank">Notebook PDF Continuous RV</a> |
|23| 25 Feb 2025| Expectation and Moments of Continuous RVs | <a href="./slides/Expectation-Moment-PDF_24_25Feb.pdf" target="_blank">Handwritten Slides PDF Expectation-Moments</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/expectation.html" target="_blank">Notebook Expectation</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/pdf-continuous.html" target="_blank">Notebook PDF Continuous RV</a> [continued] |
|24| 17 Mar 2025| Cumulative Distribution Function | <a href="./slides/CDF_17Mar.pdf" target="_blank">Handwritten Slides CDF</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/cdf.html" target="_blank">Notebook CDF</a> |
|25| 18 Mar 2025| Joint PDF and CDF + 2D Distributions + Geogebra | <a href="https://probability4datascience.com/slides/Slide_5_01.pdf" target="_blank">Slides Joint PDF and CDF</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/2d-distributions.html" target="_blank">Notebook 2D Distributions</a>, <a href="https://huggingface.co/spaces/Nipun/2d-distributions" target="_blank">HuggingFace Spaces</a>, <a href="https://www.youtube.com/watch?v=gifQWtTWqEY" target="_blank">Double Integrals Video</a>, <a href="https://www.youtube.com/watch?v=UuoVhUqWAFc" target="_blank">Instructor's Demo on Geogebra</a> |
|26| 24 Mar 2025| Joint Expectation | <a href="https://probability4datascience.com/slides/Slide_5_02.pdf" target="_blank">Slides Joint Expectation</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/embeddings-angle.html" target="_blank">Notebook Embeddings</a>, <a href="./slides/JointExpectation_24_25Mar.pdf" target="_blank">Handwritten Slides Joint Expectation</a> |
|27| 25 Mar 2025| Correlation & Covariance | <a href="https://probability4datascience.com/slides/Slide_5_03.pdf" target="_blank">Slides Covariance</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/joint-distribution-properties.html" target="_blank">Notebook Joint Distributions</a>, <a href="./slides/JointExpectation_24_25Mar.pdf" target="_blank">Handwritten Slides Joint Expectation</a> |
|28| 1 Apr 2025| Conditional Distributions | <a href="./slides/ConditionalDistributions_1Apr.pdf" target="_blank">Slides</a> |
|29| 2 Apr 2025| Sum of Random Variables | <a href="./slides/SumRandomVariables_2Apr.pdf" target="_blank">Handwritten Slides Sum of RVs</a>, <a href="https://probability4datascience.com/slides/Slide_5_06.pdf" target="_blank">Slides Sum of RVs</a>, <a href="https://probability4datascience.com/slides/Slide_5_07.pdf" target="_blank">Slides X+Y</a>, <a href="https://www.youtube.com/watch?v=IaSGqQa5O-M" target="_blank">YouTube Video</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/sum-random-vars.html" target="_blank">Notebook Sum of RVs</a> |
|30| 5 Apr 2025| Transformation of RVs | <a href="./slides/Transformation_of_Random_Variables.pdf" target="_blank">Slides Transformation</a>, <a href="./slides/transformation.ipynb" target="_blank">Notebook Transformation</a> |
|31| 7 Apr 2025| Law of Large Numbers & Inequalities | <a href="./slides/LLN-CLT_7Apr.pdf" target="_blank">Handwritten Slides LLN</a>, <a href="https://probability4datascience.com/slides/Slide_6_03.pdf" target="_blank">Slides Jensen's Inequality</a>, <a href="https://probability4datascience.com/slides/Slide_6_04.pdf" target="_blank">Slides Markov and Chebyshev Inequality</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/law-large-numbers.html" target="_blank">Notebook LLN</a>, <a href="https://github.com/nipunbatra/psdv-teaching/blob/main/apps/lln-clt.py" target="_blank">Streamlit App LLN/CLT</a> |
|32| 15 Apr 2025| Random Vectors & Multi-Variate Normal Distribution | <a href="https://nipunbatra.github.io/psdv-teaching/slides/bivariate-derivation.pdf" target="_blank">Slides Derivation of Bivariate Normal Distribution</a>, <a href="https://probability4datascience.com/slides/Slide_5_08.pdf" target="_blank">Slides Random Vector</a>, <a href="https://probability4datascience.com/slides/Slide_5_09.pdf" target="_blank">Slides Multi-dimensional Gaussian</a>, <a href="https://probability4datascience.com/slides/Slide_5_10.pdf" target="_blank">Slides Gaussian Whitening</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/random-vector.html" target="_blank">Notebook Random Vectors</a>, <a href="https://github.com/nipunbatra/psdv-teaching/blob/main/apps/normal-shape.py" target="_blank">Streamlit App Normal Shape</a> |
|33| 16 Apr 2025| Principal Component Analysis | <a href="./slides/PSDV_PCA_16Apr.pdf" target="_blank">Slides PCA</a>, <a href="https://youtu.be/PFDu9oVAE-g?si=a5tyEMpMRSwCt8be" target="_blank">3B1B Video Eigenvalues & Eigenvectors</a> |

</div>