---
title: "Lectures"
---

::: {.callout-tip}
## Summary

* [Github repo containing source code for lectures and notebooks](https://github.com/nipunbatra/psdv-teaching)
* [Rendered Lecture notebooks](https://nipunbatra.github.io/psdv-teaching/notebooks.html)
* [YouTube playlist containing recordings](https://www.youtube.com/watch?v=CAzR00au0T0&list=PLftoLyLEwECCTFpc8_-gV8NqG_LgdL3Uy&index=1) 

Content will get added here as the course progresses

:::


| Lecture # |    Date     | Topic          | Material | 
| :------: | :--------: | :-------------------------: |:-------------------:| 
|     0     | 06 Jan 2025 | Introduction and Logistics |  
|1| 07 Jan 2025| NumPy| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/intro-numpy.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=CAzR00au0T0" target="_blank">Youtube</a> |
|2| 08 Jan 2025| Lab 1: NumPy| <a href="https://colab.research.google.com/drive/169vg_FV35sJ8irVXU82RrTwlR762Ph2g?usp=sharing" target="_blank">Colab</a> |
|3| 13 Jan 2025| Pandas| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/introduction-pandas.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=iaQDhwFkAhA" target="_blank">Youtube</a> |
|4| 14 Jan 2025| Matplotlib| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/introduction-matplotlib.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=ERu46g5EzVk" target="_blank">Youtube</a> |
|5| 15 Jan 2025| Lab Viva 1|
|6| 20 Jan 2025| Lab 2: Pandas| <a href="https://colab.research.google.com/drive/1pmt8hSfwzhp8ke3uXsGrOt4XELdoTmr1?usp=sharing" target="_blank">Colab</a> |
|7| 21 Jan 2025| Set Theory| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/set.html" target="_blank">Notebook</a>, <a href="https://probability4datascience.com/slides/Slide_2_01.pdf" target="_blank">Slides</a> |
|8| 22 Jan 2025| Lab 2: Pandas (continued)|
|9| 23 Jan 2025| Jupyter Widgets| <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/widgets.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=BJAaZaKxf00" target="_blank">YouTube</a> |
|10| 23 Jan 2025| More Set Theory Questions | <a href="https://colab.research.google.com/drive/1RrjF2VZDcst0iUgW5zrpsBy-VWUfjtkJ?usp=sharing" target="_blank">Colab</a> |
|11| 27 Jan 2025| Set Theory (continued)| <a href="https://probability4datascience.com/slides/Slide_2_01.pdf" target="_blank">Slides</a>, <a href="./slides/Set-Theory_27Jan.pdf" target="_blank">Handwritten Slides</a> |
|12| 28 Jan 2025| Probability| <a href="https://probability4datascience.com/slides/Slide_2_02.pdf" target="_blank">Slides1</a>, <a href="https://probability4datascience.com/slides/Slide_2_03.pdf" target="_blank">Slides2</a>, <a href="./slides/Probability_28Jan.pdf" target="_blank">Handwritten Slides</a> |
|13| 29 Jan 2025| Lab Viva 2|
|14| 03 Feb 2025| Conditional Probability & Independence | <a href="https://probability4datascience.com/slides/Slide_2_04.pdf" target="_blank">Slides Conditional</a>, <a href="https://probability4datascience.com/slides/Slide_2_05.pdf" target="_blank">Slides Independence</a>, <a href="./slides/Conditional_Bayes_3_4Feb.pdf" target="_blank">Handwritten Slides</a> |
|15| 04 Feb 2025| Bayes Theorem & Total Probability | <a href="https://probability4datascience.com/slides/Slide_2_06.pdf" target="_blank">Slides</a>, <a href="./slides/Conditional_Bayes_3_4Feb.pdf" target="_blank">Handwritten Slides (continued)</a> |
|16| 05 Feb 2025| Quiz 1|
|17| 10 Feb 2025| Random Variables + Quiz Discussion | <a href="https://probability4datascience.com/slides/Slide_3_01.pdf" target="_blank">Slides</a> |
|18| 11 Feb 2025| Probability Mass Function | <a href="https://probability4datascience.com/slides/Slide_3_02.pdf" target="_blank">Slides</a>, <a href="https://nipunbatra.github.io/psdv-teaching/notebooks/pmf-discrete.html" target="_blank">Notebook</a>, <a href="https://www.youtube.com/watch?v=_VU6QMC6XE0" target="_blank">YouTube</a> |